/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART1TXSRC_UART_TX 0x00u /*!<@brief UART 1 transmit data source select: UART1_TX pin */

/*! @name PORTE1 (number 2), J2[20]/UART1_RX_TGTMCU
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_DEBUG_UART_RX_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_DEBUG_UART_RX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_DEBUG_UART_RX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTA2 (number 24), J1[8]/GREEN_LED
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LEDRGB_GREEN_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_LEDRGB_GREEN_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_LEDRGB_GREEN_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*! @name PORTA1 (number 23), J2[4]/LSCAN_SI
  @{ */

/* Symbols to be used with GPIO driver */
#define LSCAN_CAM_LSCAN_CAM_SI_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define LSCAN_CAM_LSCAN_CAM_SI_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LSCAN_CAM_LSCAN_CAM_SI_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define LSCAN_CAM_LSCAN_CAM_SI_PIN 1U                   /*!<@brief PORT pin number */
#define LSCAN_CAM_LSCAN_CAM_SI_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTA4 (number 26), J1[10]/LSCAN_CK
  @{ */

/* Symbols to be used with GPIO driver */
#define LSCAN_CAM_LSCAN_CAM_CK_GPIO GPIOA               /*!<@brief GPIO peripheral base pointer */
#define LSCAN_CAM_LSCAN_CAM_CK_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LSCAN_CAM_LSCAN_CAM_CK_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define LSCAN_CAM_LSCAN_CAM_CK_PIN 4U                   /*!<@brief PORT pin number */
#define LSCAN_CAM_LSCAN_CAM_CK_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTB0 (number 35), J24[2]/LSCAN_AO
  @{ */

/* Symbols to be used with PORT driver */
#define LSCAN_CAM_LSCAN_CAM_AO_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LSCAN_CAM_LSCAN_CAM_AO_PIN 0U                   /*!<@brief PORT pin number */
#define LSCAN_CAM_LSCAN_CAM_AO_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LSCAN_CAM(void);

/*! @name PORTA4 (number 26), J1[10]/LSCAN_CK
  @{ */

/* Symbols to be used with PORT driver */
#define LSCAN_CAM_DEINIT_LSCAN_CAM_CK_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define LSCAN_CAM_DEINIT_LSCAN_CAM_CK_PIN 4U                   /*!<@brief PORT pin number */
#define LSCAN_CAM_DEINIT_LSCAN_CAM_CK_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*! @name PORTB0 (number 35), J24[2]/LSCAN_AO
  @{ */

/* Symbols to be used with PORT driver */
#define LSCAN_CAM_DEINIT_LSCAN_CAM_AO_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LSCAN_CAM_DEINIT_LSCAN_CAM_AO_PIN 0U                   /*!<@brief PORT pin number */
#define LSCAN_CAM_DEINIT_LSCAN_CAM_AO_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief This is a de-initialization function for 'LSCAN_CAM' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 */
void LSCAN_CAM_deinit(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
